import { SchemaTypeDefinition } from 'sanity'

const iframe: SchemaTypeDefinition = {
  name: 'bandcamp',
  title: 'Bandcamp embed',
  type: 'document',
  fields: [
    {
      name: 'albumId',
      title: 'Album ID',
      description:
        'The ID to reference the resource you want to embed. You can find the ID in the HTML embed code generated by clicking "Share/Embed" on Bandcamp.',
      type: 'number',
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'trackId',
      title: 'Track ID',
      description:
        'If you are sharing a specific track, this is required. To share the entire album, leave this blank.',
      type: 'number',
    },
  ],
}

export default iframe
